### PR TITLE
Added row_kron2 (fast row_kron)

### PR DESCRIPTION
**Pull request by albep**
Hi Spencer,

I've added row_kron2 to the util.jl file. Looking forward to seeing it in the compecon master branch!

(My first PR)

Alberto

### CODE REVIEW

**Comment by sglyon** [comment]
Thanks for doing this. Will you rename this to row_kron and replace the existing method for sparse matrices? I don't see any reason to maintain the older slow version.

**Comment by albep** [comment]
Done it, but I'm not sure whether you can see it

**Comment by sglyon** [comment]
Yep, that was perfect. Thanks.

**Comment by sglyon** [comment]
Now the question is what should we do for cases where `A<:Array{Float64,2}` and `B<:SparseMatrixCSC{Float64}` or the other way around (one sparse, one dense). 

It might be best to just convert the sparse one to dense and then call sparse on the output. What do you think?

**Comment by albep** [comment]
In my code I run into that issue and I converted the dense to sparse, then
applied row_kron on sparses. Do you think the other way around is faster?
It should depend on how sparse a matrix is right. It would be nice to
compare the performances, then decide ;)

**Comment by sglyon** [comment]
Interesting. We should definitely compare between the two methods. 

I won't get to that in the immediate future, but if you feel up for it go ahead and have a crack at it!

**Comment by albep** [comment]
It works fine as it is now, but I'll take a look at that asap and let you
know

**Pull request merged**
